package Hibernate;
// Generated 20-apr-2013 22:03:31 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Geregistreerdegebruikers generated by hbm2java
 */
public class Geregistreerdegebruikers  implements java.io.Serializable {


     private Integer gebrId;
     private String gebrNaam;
     private String gebrAdres;
     private Date gebrGebDat;
     private String gebrPass;
     private Set ticketses = new HashSet(0);

    public Geregistreerdegebruikers() {
    }

	
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat, String gebrPass) {
        this.gebrNaam = gebrNaam;
        this.gebrAdres = gebrAdres;
        this.gebrGebDat = gebrGebDat;
        this.gebrPass = gebrPass;
    }
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat, String gebrPass, Set ticketses) {
       this.gebrNaam = gebrNaam;
       this.gebrAdres = gebrAdres;
       this.gebrGebDat = gebrGebDat;
       this.gebrPass = gebrPass;
       this.ticketses = ticketses;
    }
   
    public Integer getGebrId() {
        return this.gebrId;
    }
    
    public void setGebrId(Integer gebrId) {
        this.gebrId = gebrId;
    }
    public String getGebrNaam() {
        return this.gebrNaam;
    }
    
    public void setGebrNaam(String gebrNaam) {
        this.gebrNaam = gebrNaam;
    }
    public String getGebrAdres() {
        return this.gebrAdres;
    }
    
    public void setGebrAdres(String gebrAdres) {
        this.gebrAdres = gebrAdres;
    }
    public Date getGebrGebDat() {
        return this.gebrGebDat;
    }
    
    public void setGebrGebDat(Date gebrGebDat) {
        this.gebrGebDat = gebrGebDat;
    }
    public String getGebrPass() {
        return this.gebrPass;
    }
    
    public void setGebrPass(String gebrPass) {
        this.gebrPass = gebrPass;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


